name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say hello
        run: |
          echo "Hello World!"
      - name: Get current time
        run: |
          echo "The time is now $(date -u +%H:%M:%S)"
      - name: List files
        run: |
          ls -a
      - name: look calendar
        run: |
          cal